<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebEncRegister\Module'                        => __DIR__ . '/Module.php',
    'WebEncRegister\Controller\WebEncRegisterControllerController' => __DIR__ . '/src/WebEncRegister/Controller/WebEncRegisterControllerController.php',
    'WebEncRegisterTest\Framework\TestCase'        => __DIR__ . '/tests/WebEncRegister/Framework/TestCase.php',
    'WebEncRegisterTest\SampleTest'                => __DIR__ . '/tests/WebEncRegister/SampleTest.php',
);
