<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Downloads\Module'                        => __DIR__ . '/Module.php',
    'Downloads\Controller\DownloadsControllerController' => __DIR__ . '/src/Downloads/Controller/DownloadsControllerController.php',
    'DownloadsTest\Framework\TestCase'        => __DIR__ . '/tests/Downloads/Framework/TestCase.php',
    'DownloadsTest\SampleTest'                => __DIR__ . '/tests/Downloads/SampleTest.php',
);
