<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Account\Module'                        => __DIR__ . '/Module.php',
    'Account\Controller\AccountInfoControllerController' => __DIR__ . '/src/Account/Controller/AccountInfoControllerController.php',
    'AccountTest\Framework\TestCase'        => __DIR__ . '/tests/Account/Framework/TestCase.php',
    'AccountTest\SampleTest'                => __DIR__ . '/tests/Account/SampleTest.php',
);
