<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UpdatePass\Module'                        => __DIR__ . '/Module.php',
    'UpdatePass\Controller\UpdatePassControllerController' => __DIR__ . '/src/UpdatePass/Controller/UpdatePassControllerController.php',
    'UpdatePassTest\Framework\TestCase'        => __DIR__ . '/tests/UpdatePass/Framework/TestCase.php',
    'UpdatePassTest\SampleTest'                => __DIR__ . '/tests/UpdatePass/SampleTest.php',
);
