<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MarkMonkey\Module'                        => __DIR__ . '/Module.php',
    'MarkMonkey\Controller\MarkMonkeyControllerController' => __DIR__ . '/src/MarkMonkey/Controller/MarkMonkeyControllerController.php',
    'MarkMonkeyTest\Framework\TestCase'        => __DIR__ . '/tests/MarkMonkey/Framework/TestCase.php',
    'MarkMonkeyTest\SampleTest'                => __DIR__ . '/tests/MarkMonkey/SampleTest.php',
);
