<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SignIn\Module'                        => __DIR__ . '/Module.php',
    'SignIn\Controller\SignInControllerController' => __DIR__ . '/src/SignIn/Controller/SignInControllerController.php',
    'SignInTest\Framework\TestCase'        => __DIR__ . '/tests/SignIn/Framework/TestCase.php',
    'SignInTest\SampleTest'                => __DIR__ . '/tests/SignIn/SampleTest.php',
);
