<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DigitalRiver\Module'                        => __DIR__ . '/Module.php',
    'DigitalRiver\Controller\DROrderControllerController' => __DIR__ . '/src/DigitalRiver/Controller/DROrderControllerController.php',
    'DigitalRiverTest\Framework\TestCase'        => __DIR__ . '/tests/DigitalRiver/Framework/TestCase.php',
    'DigitalRiverTest\SampleTest'                => __DIR__ . '/tests/DigitalRiver/SampleTest.php',
);
