<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'XmlOutput\Module'                        => __DIR__ . '/Module.php',
    'XmlOutput\Controller\IndexControllerController' => __DIR__ . '/src/XmlOutput/Controller/IndexControllerController.php',
    'XmlOutputTest\Framework\TestCase'        => __DIR__ . '/tests/XmlOutput/Framework/TestCase.php',
    'XmlOutputTest\SampleTest'                => __DIR__ . '/tests/XmlOutput/SampleTest.php',
);
