<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Web64base\Module'                        => __DIR__ . '/Module.php',
    'Web64base\Controller\Web64BaseControllerController' => __DIR__ . '/src/Web64base/Controller/Web64BaseControllerController.php',
    'Web64baseTest\Framework\TestCase'        => __DIR__ . '/tests/Web64base/Framework/TestCase.php',
    'Web64baseTest\SampleTest'                => __DIR__ . '/tests/Web64base/SampleTest.php',
);
